# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TxLiveTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TxLiveTest

pod 'Masonry', '~> 1.0.2'
pod 'BlocksKit'
pod 'ReactiveCocoa', :git => 'https://github.com/zhao0/ReactiveCocoa.git', :tag => '2.5.2'
pod 'SDWebImage', '~> 4.0'
pod 'BarrageRenderer','~>2.1.0'
pod 'YYKit'





#pod 'OYModule' , :path=>'../OYModule'
#pod 'OYModule/UIKit' , :path=>'../OYModule'
#pod 'OYModule/NSObject' , :path=>'../OYModule'
#pod 'OYModule/OYBarrageRenderer' , :path=>'../OYModule'

end
